export interface GrammarDocSection {
  id: string;
  bookLevelId: "fundamentals" | "tn1" | "tn2" | "tn3" | "summit1" | "summit2";
  bookTitle: string;
  topicTitle: string;
  category: "Verb Tenses" | "Modals & Auxiliaries" | "Sentence Structure" | "Clauses & Conditionals" | "Vocabulary & Mechanics";
  summary: string;
  formula: string;
  rules: string[];
  examples: Array<{ en: string; es: string; note?: string }>;
  commonMistakes: Array<{ wrong: string; correct: string; explanation: string }>;
  topNotchUnitRef: string;
}

export const ENGLISH_GRAMMAR_DOCS: GrammarDocSection[] = [
  // Fundamentals (1-14)
  { id: "fund-1", bookLevelId: "fundamentals", bookTitle: "Top Notch Fundamentals", topicTitle: "Names and Occupations", category: "Vocabulary & Mechanics", summary: "Introducción básica. Uso del verbo 'to be'.", formula: "S + am/is/are + C", rules: ["I am", "He/She/It is", "We/They/You are"], examples: [{ en: "I am John.", es: "Soy John." }], commonMistakes: [{ wrong: "I name John.", correct: "My name is John.", explanation: "Uso correcto de 'to be'." }], topNotchUnitRef: "Unit 1" },
  { id: "fund-2", bookLevelId: "fundamentals", bookTitle: "Top Notch Fundamentals", topicTitle: "About People", category: "Vocabulary & Mechanics", summary: "Identificación de personas.", formula: "Wh + is + S?", rules: ["Usa Who para personas", "Usa What para objetos"], examples: [{ en: "Who is he?", es: "¿Quién es él?" }], commonMistakes: [{ wrong: "Who he?", correct: "Who is he?", explanation: "Falta el verbo." }], topNotchUnitRef: "Unit 2" },
  { id: "fund-3", bookLevelId: "fundamentals", bookTitle: "Top Notch Fundamentals", topicTitle: "Places and How to Get There", category: "Vocabulary & Mechanics", summary: "Direcciones y lugares.", formula: "Where is + S?", rules: ["Usa Where para ubicación"], examples: [{ en: "Where is the bank?", es: "¿Dónde está el banco?" }], commonMistakes: [{ wrong: "Where the bank?", correct: "Where is the bank?", explanation: "Falta el verbo." }], topNotchUnitRef: "Unit 3" },
  { id: "fund-4", bookLevelId: "fundamentals", bookTitle: "Top Notch Fundamentals", topicTitle: "Family", category: "Vocabulary & Mechanics", summary: "Describir familia.", formula: "S + have/has + family member", rules: ["I/You/We/They have", "He/She has"], examples: [{ en: "I have a sister.", es: "Tengo una hermana." }], commonMistakes: [{ wrong: "She have a sister.", correct: "She has a sister.", explanation: "Uso correcto de has." }], topNotchUnitRef: "Unit 4" },
  { id: "fund-5", bookLevelId: "fundamentals", bookTitle: "Top Notch Fundamentals", topicTitle: "Events and Times", category: "Vocabulary & Mechanics", summary: "Hora y fechas.", formula: "It is + Time", rules: ["Usa 'at' para horas"], examples: [{ en: "It is at 8:00.", es: "Es a las 8:00." }], commonMistakes: [{ wrong: "It is in 8:00.", correct: "It is at 8:00.", explanation: "Preposición at para horas." }], topNotchUnitRef: "Unit 5" },
  { id: "fund-6", bookLevelId: "fundamentals", bookTitle: "Top Notch Fundamentals", topicTitle: "Clothes", category: "Vocabulary & Mechanics", summary: "Vocabulario de ropa.", formula: "I want + item", rules: ["Necesito + articulo"], examples: [{ en: "I want a shirt.", es: "Quiero una camisa." }], commonMistakes: [{ wrong: "I want shirt.", correct: "I want a shirt.", explanation: "Requiere articulo." }], topNotchUnitRef: "Unit 6" },
  { id: "fund-7", bookLevelId: "fundamentals", bookTitle: "Top Notch Fundamentals", topicTitle: "Activities", category: "Verb Tenses", summary: "Presente continuo.", formula: "S + am/is/are + verb-ing", rules: ["Acciones en progreso"], examples: [{ en: "I am eating.", es: "Estoy comiendo." }], commonMistakes: [{ wrong: "I eating.", correct: "I am eating.", explanation: "Am es necesario." }], topNotchUnitRef: "Unit 7" },
  { id: "fund-8", bookLevelId: "fundamentals", bookTitle: "Top Notch Fundamentals", topicTitle: "Home and Office", category: "Vocabulary & Mechanics", summary: "Descripción de lugares.", formula: "There is/are + N", rules: ["Is para contables singulares", "Are para plurales"], examples: [{ en: "There is a desk.", es: "Hay un escritorio." }], commonMistakes: [{ wrong: "There are a desk.", correct: "There is a desk.", explanation: "Singular usa is." }], topNotchUnitRef: "Unit 8" },
  { id: "fund-9", bookLevelId: "fundamentals", bookTitle: "Top Notch Fundamentals", topicTitle: "Activities and Plans", category: "Verb Tenses", summary: "Presente continuo y planes.", formula: "S + am/is/are + verb-ing", rules: ["Igual que Unit 7"], examples: [{ en: "I am studying.", es: "Estoy estudiando." }], commonMistakes: [{ wrong: "I am study.", correct: "I am studying.", explanation: "Verbo necesita -ing." }], topNotchUnitRef: "Unit 9" },
  { id: "fund-10", bookLevelId: "fundamentals", bookTitle: "Top Notch Fundamentals", topicTitle: "Food", category: "Vocabulary & Mechanics", summary: "Comida y gustos.", formula: "I like + N", rules: ["Gustos"], examples: [{ en: "I like apples.", es: "Me gustan las manzanas." }], commonMistakes: [{ wrong: "I likes apples.", correct: "I like apples.", explanation: "I no lleva 's'." }], topNotchUnitRef: "Unit 10" },
  { id: "fund-11", bookLevelId: "fundamentals", bookTitle: "Top Notch Fundamentals", topicTitle: "Past Events", category: "Verb Tenses", summary: "Pasado simple.", formula: "S + verb-ed", rules: ["Verbos regulares"], examples: [{ en: "I played.", es: "Jugué." }], commonMistakes: [{ wrong: "I play.", correct: "I played.", explanation: "Pasado requiere -ed." }], topNotchUnitRef: "Unit 11" },
  { id: "fund-12", bookLevelId: "fundamentals", bookTitle: "Top Notch Fundamentals", topicTitle: "Appearance and Health", category: "Vocabulary & Mechanics", summary: "Salud y apariencia.", formula: "I have + N", rules: ["Síntomas"], examples: [{ en: "I have a headache.", es: "Tengo dolor de cabeza." }], commonMistakes: [{ wrong: "I am headache.", correct: "I have a headache.", explanation: "Se tiene dolor." }], topNotchUnitRef: "Unit 12" },
  { id: "fund-13", bookLevelId: "fundamentals", bookTitle: "Top Notch Fundamentals", topicTitle: "Abilities and Requests", category: "Modals & Auxiliaries", summary: "Habilidades.", formula: "S + can + V", rules: ["Can no cambia"], examples: [{ en: "I can swim.", es: "Sé nadar." }], commonMistakes: [{ wrong: "I can swims.", correct: "I can swim.", explanation: "Verbo base." }], topNotchUnitRef: "Unit 13" },
  { id: "fund-14", bookLevelId: "fundamentals", bookTitle: "Top Notch Fundamentals", topicTitle: "Life Events", category: "Verb Tenses", summary: "Planes a futuro.", formula: "S + will/going to + V", rules: ["Futuro"], examples: [{ en: "I will go.", es: "Iré." }], commonMistakes: [{ wrong: "I will going.", correct: "I will go.", explanation: "Verbo base." }], topNotchUnitRef: "Unit 14" },
  
  // TN1 (1-10)
  { id: "tn1-1", bookLevelId: "tn1", bookTitle: "Top Notch 1", topicTitle: "Getting Acquainted", category: "Vocabulary & Mechanics", summary: "Presentaciones.", formula: "I'm + Name", rules: ["Presentaciones"], examples: [{ en: "I'm John.", es: "Soy John." }], commonMistakes: [{ wrong: "Me John.", correct: "I'm John.", explanation: "Sujeto necesario." }], topNotchUnitRef: "Unit 1" },
  { id: "tn1-2", bookLevelId: "tn1", bookTitle: "Top Notch 1", topicTitle: "Going Out", category: "Vocabulary & Mechanics", summary: "Invitaciones.", formula: "Would you like to + V?", rules: ["Invitaciones"], examples: [{ en: "Would you like to go?", es: "¿Te gustaría ir?" }], commonMistakes: [{ wrong: "Do you like to go?", correct: "Would you like to go?", explanation: "Would para invitación." }], topNotchUnitRef: "Unit 2" },
  { id: "tn1-3", bookLevelId: "tn1", bookTitle: "Top Notch 1", topicTitle: "The Extended Family", category: "Vocabulary & Mechanics", summary: "Familia.", formula: "S + have + family", rules: ["Familia"], examples: [{ en: "I have a brother.", es: "Tengo un hermano." }], commonMistakes: [{ wrong: "I have brother.", correct: "I have a brother.", explanation: "Articulo." }], topNotchUnitRef: "Unit 3" },
  { id: "tn1-4", bookLevelId: "tn1", bookTitle: "Top Notch 1", topicTitle: "Food and Restaurants", category: "Vocabulary & Mechanics", summary: "Restaurantes.", formula: "I would like + N", rules: ["Pedidos"], examples: [{ en: "I would like a pizza.", es: "Quisiera una pizza." }], commonMistakes: [{ wrong: "I want pizza.", correct: "I would like a pizza.", explanation: "Más formal." }], topNotchUnitRef: "Unit 4" },
  { id: "tn1-5", bookLevelId: "tn1", bookTitle: "Top Notch 1", topicTitle: "Technology and You", category: "Vocabulary & Mechanics", summary: "Tecnología.", formula: "S + is + adjective", rules: ["Descripciones"], examples: [{ en: "It is new.", es: "Es nuevo." }], commonMistakes: [{ wrong: "It new.", correct: "It is new.", explanation: "Verbo to be." }], topNotchUnitRef: "Unit 5" },
  { id: "tn1-6", bookLevelId: "tn1", bookTitle: "Top Notch 1", topicTitle: "Staying in Shape", category: "Vocabulary & Mechanics", summary: "Salud.", formula: "You should + V", rules: ["Consejos"], examples: [{ en: "You should eat.", es: "Deberías comer." }], commonMistakes: [{ wrong: "You should to eat.", correct: "You should eat.", explanation: "Sin 'to'." }], topNotchUnitRef: "Unit 6" },
  { id: "tn1-7", bookLevelId: "tn1", bookTitle: "Top Notch 1", topicTitle: "On Vacation", category: "Verb Tenses", summary: "Vacaciones.", formula: "S + verb-ed (past)", rules: ["Verbos regulares"], examples: [{ en: "I traveled.", es: "Viajé." }], commonMistakes: [{ wrong: "I travel.", correct: "I traveled.", explanation: "Pasado." }], topNotchUnitRef: "Unit 7" },
  { id: "tn1-8", bookLevelId: "tn1", bookTitle: "Top Notch 1", topicTitle: "Shopping for Clothes", category: "Vocabulary & Mechanics", summary: "Compras.", formula: "How much is + N?", rules: ["Precios"], examples: [{ en: "How much is it?", es: "¿Cuánto cuesta?" }], commonMistakes: [{ wrong: "How much it?", correct: "How much is it?", explanation: "Verbo ser." }], topNotchUnitRef: "Unit 8" },
  { id: "tn1-9", bookLevelId: "tn1", bookTitle: "Top Notch 1", topicTitle: "Taking Transportation", category: "Vocabulary & Mechanics", summary: "Transporte.", formula: "When does it + V?", rules: ["Horarios"], examples: [{ en: "When does it leave?", es: "¿Cuándo sale?" }], commonMistakes: [{ wrong: "When it leave?", correct: "When does it leave?", explanation: "Auxiliar does." }], topNotchUnitRef: "Unit 9" },
  { id: "tn1-10", bookLevelId: "tn1", bookTitle: "Top Notch 1", topicTitle: "Spending Money", category: "Vocabulary & Mechanics", summary: "Dinero.", formula: "S + need to + V", rules: ["Necesidad"], examples: [{ en: "I need to pay.", es: "Necesito pagar." }], commonMistakes: [{ wrong: "I need pay.", correct: "I need to pay.", explanation: "Uso de to." }], topNotchUnitRef: "Unit 10" },

  { id: "tn2-1", bookLevelId: "tn2", bookTitle: "Top Notch 2", topicTitle: "Getting Acquainted", category: "Vocabulary & Mechanics", summary: "Reencuentro.", formula: "S + have + V-ed", rules: [], examples: [], commonMistakes: [], topNotchUnitRef: "Unit 1" },
  { id: "tn2-2", bookLevelId: "tn2", bookTitle: "Top Notch 2", topicTitle: "Going to the Movies", category: "Vocabulary & Mechanics", summary: "Cine.", formula: "S + enjoy + V-ing", rules: [], examples: [], commonMistakes: [], topNotchUnitRef: "Unit 2" },
  { id: "tn2-3", bookLevelId: "tn2", bookTitle: "Top Notch 2", topicTitle: "Staying in Hotels", category: "Vocabulary & Mechanics", summary: "Hoteles.", formula: "S + want + N", rules: [], examples: [], commonMistakes: [], topNotchUnitRef: "Unit 3" },
  { id: "tn2-4", bookLevelId: "tn2", bookTitle: "Top Notch 2", topicTitle: "Cars and Driving", category: "Vocabulary & Mechanics", summary: "Autos.", formula: "S + drive + N", rules: [], examples: [], commonMistakes: [], topNotchUnitRef: "Unit 4" },
  { id: "tn2-5", bookLevelId: "tn2", bookTitle: "Top Notch 2", topicTitle: "Personal Care", category: "Vocabulary & Mechanics", summary: "Cuidado.", formula: "S + need + N", rules: [], examples: [], commonMistakes: [], topNotchUnitRef: "Unit 5" },
  { id: "tn2-6", bookLevelId: "tn2", bookTitle: "Top Notch 2", topicTitle: "Eating Well", category: "Vocabulary & Mechanics", summary: "Comida.", formula: "S + eat + N", rules: [], examples: [], commonMistakes: [], topNotchUnitRef: "Unit 6" },
  { id: "tn2-7", bookLevelId: "tn2", bookTitle: "Top Notch 2", topicTitle: "About Personality", category: "Vocabulary & Mechanics", summary: "Personalidad.", formula: "S + is + Adj", rules: [], examples: [], commonMistakes: [], topNotchUnitRef: "Unit 7" },
  { id: "tn2-8", bookLevelId: "tn2", bookTitle: "Top Notch 2", topicTitle: "The Arts", category: "Vocabulary & Mechanics", summary: "Arte.", formula: "S + like + N", rules: [], examples: [], commonMistakes: [], topNotchUnitRef: "Unit 8" },
  { id: "tn2-9", bookLevelId: "tn2", bookTitle: "Top Notch 2", topicTitle: "Living in Cyberspace", category: "Vocabulary & Mechanics", summary: "Internet.", formula: "S + use + N", rules: [], examples: [], commonMistakes: [], topNotchUnitRef: "Unit 9" },
  { id: "tn2-10", bookLevelId: "tn2", bookTitle: "Top Notch 2", topicTitle: "Ethics and Values", category: "Vocabulary & Mechanics", summary: "Ética.", formula: "S + should + V", rules: [], examples: [], commonMistakes: [], topNotchUnitRef: "Unit 10" },
  { id: "tn3-1", bookLevelId: "tn3", bookTitle: "Top Notch 3", topicTitle: "Make Small Talk", category: "Vocabulary & Mechanics", summary: "Conversación.", formula: "S + v", rules: [], examples: [], commonMistakes: [], topNotchUnitRef: "Unit 1" },
  { id: "tn3-2", bookLevelId: "tn3", bookTitle: "Top Notch 3", topicTitle: "Health Matters", category: "Vocabulary & Mechanics", summary: "Salud.", formula: "S + feel + Adj", rules: [], examples: [], commonMistakes: [], topNotchUnitRef: "Unit 2" },
  { id: "tn3-3", bookLevelId: "tn3", bookTitle: "Top Notch 3", topicTitle: "Getting Things Done", category: "Vocabulary & Mechanics", summary: "Tareas.", formula: "S + fix + N", rules: [], examples: [], commonMistakes: [], topNotchUnitRef: "Unit 3" },
  { id: "tn3-4", bookLevelId: "tn3", bookTitle: "Top Notch 3", topicTitle: "Reading for Pleasure", category: "Vocabulary & Mechanics", summary: "Lectura.", formula: "S + read + N", rules: [], examples: [], commonMistakes: [], topNotchUnitRef: "Unit 4" },
  { id: "tn3-5", bookLevelId: "tn3", bookTitle: "Top Notch 3", topicTitle: "Natural Disasters", category: "Vocabulary & Mechanics", summary: "Clima.", formula: "S + is + Adj", rules: [], examples: [], commonMistakes: [], topNotchUnitRef: "Unit 5" },
  { id: "tn3-6", bookLevelId: "tn3", bookTitle: "Top Notch 3", topicTitle: "Life Plans", category: "Vocabulary & Mechanics", summary: "Planes.", formula: "S + plan + to + V", rules: [], examples: [], commonMistakes: [], topNotchUnitRef: "Unit 6" },
  { id: "tn3-7", bookLevelId: "tn3", bookTitle: "Top Notch 3", topicTitle: "Holidays", category: "Vocabulary & Mechanics", summary: "Fiestas.", formula: "S + celebrate + N", rules: [], examples: [], commonMistakes: [], topNotchUnitRef: "Unit 7" },
  { id: "tn3-8", bookLevelId: "tn3", bookTitle: "Top Notch 3", topicTitle: "Inventions", category: "Vocabulary & Mechanics", summary: "Inventos.", formula: "S + invent + N", rules: [], examples: [], commonMistakes: [], topNotchUnitRef: "Unit 8" },
  { id: "tn3-9", bookLevelId: "tn3", bookTitle: "Top Notch 3", topicTitle: "Controversial", category: "Vocabulary & Mechanics", summary: "Debates.", formula: "S + discuss + N", rules: [], examples: [], commonMistakes: [], topNotchUnitRef: "Unit 9" },
  { id: "tn3-10", bookLevelId: "tn3", bookTitle: "Top Notch 3", topicTitle: "Beautiful World", category: "Vocabulary & Mechanics", summary: "Mundo.", formula: "S + visit + N", rules: [], examples: [], commonMistakes: [], topNotchUnitRef: "Unit 10" },
  { id: "sum1-1", bookLevelId: "summit1", bookTitle: "Summit 1", topicTitle: "Outlook", category: "Vocabulary & Mechanics", summary: "Personalidad.", formula: "S + feel + Adj", rules: [], examples: [], commonMistakes: [], topNotchUnitRef: "Unit 1" },
  { id: "sum1-2", bookLevelId: "summit1", bookTitle: "Summit 1", topicTitle: "Arts", category: "Vocabulary & Mechanics", summary: "Arte.", formula: "S + like + N", rules: [], examples: [], commonMistakes: [], topNotchUnitRef: "Unit 2" },
  { id: "sum1-3", bookLevelId: "summit1", bookTitle: "Summit 1", topicTitle: "Money", category: "Vocabulary & Mechanics", summary: "Dinero.", formula: "S + spend + N", rules: [], examples: [], commonMistakes: [], topNotchUnitRef: "Unit 3" },
  { id: "sum1-4", bookLevelId: "summit1", bookTitle: "Summit 1", topicTitle: "Clothing", category: "Vocabulary & Mechanics", summary: "Ropa.", formula: "S + wear + N", rules: [], examples: [], commonMistakes: [], topNotchUnitRef: "Unit 4" },
  { id: "sum1-5", bookLevelId: "summit1", bookTitle: "Summit 1", topicTitle: "Communities", category: "Vocabulary & Mechanics", summary: "Sociedad.", formula: "S + live + N", rules: [], examples: [], commonMistakes: [], topNotchUnitRef: "Unit 5" },
  { id: "sum1-6", bookLevelId: "summit1", bookTitle: "Summit 1", topicTitle: "Animals", category: "Vocabulary & Mechanics", summary: "Animales.", formula: "S + like + N", rules: [], examples: [], commonMistakes: [], topNotchUnitRef: "Unit 6" },
  { id: "sum1-7", bookLevelId: "summit1", bookTitle: "Summit 1", topicTitle: "Advertising", category: "Vocabulary & Mechanics", summary: "Publicidad.", formula: "S + buy + N", rules: [], examples: [], commonMistakes: [], topNotchUnitRef: "Unit 7" },
  { id: "sum1-8", bookLevelId: "summit1", bookTitle: "Summit 1", topicTitle: "Family Trends", category: "Vocabulary & Mechanics", summary: "Familia.", formula: "S + have + N", rules: [], examples: [], commonMistakes: [], topNotchUnitRef: "Unit 8" },
  { id: "sum1-9", bookLevelId: "summit1", bookTitle: "Summit 1", topicTitle: "Facts", category: "Vocabulary & Mechanics", summary: "Hechos.", formula: "S + know + N", rules: [], examples: [], commonMistakes: [], topNotchUnitRef: "Unit 9" },
  { id: "sum1-10", bookLevelId: "summit1", bookTitle: "Summit 1", topicTitle: "Free Time", category: "Vocabulary & Mechanics", summary: "Ocio.", formula: "S + enjoy + V-ing", rules: [], examples: [], commonMistakes: [], topNotchUnitRef: "Unit 10" },
  { id: "sum2-1", bookLevelId: "summit2", bookTitle: "Summit 2", topicTitle: "Dreams", category: "Vocabulary & Mechanics", summary: "Metas.", formula: "S + want + to + V", rules: [], examples: [], commonMistakes: [], topNotchUnitRef: "Unit 1" },
  { id: "sum2-2", bookLevelId: "summit2", bookTitle: "Summit 2", topicTitle: "Responsibility", category: "Vocabulary & Mechanics", summary: "Ética.", formula: "S + be + responsible", rules: [], examples: [], commonMistakes: [], topNotchUnitRef: "Unit 2" },
  { id: "sum2-3", bookLevelId: "summit2", bookTitle: "Summit 2", topicTitle: "Hardships", category: "Vocabulary & Mechanics", summary: "Miedo.", formula: "S + fear + N", rules: [], examples: [], commonMistakes: [], topNotchUnitRef: "Unit 3" },
  { id: "sum2-4", bookLevelId: "summit2", bookTitle: "Summit 2", topicTitle: "Others", category: "Vocabulary & Mechanics", summary: "Relaciones.", formula: "S + like + N", rules: [], examples: [], commonMistakes: [], topNotchUnitRef: "Unit 4" },
  { id: "sum2-5", bookLevelId: "summit2", bookTitle: "Summit 2", topicTitle: "Humor", category: "Vocabulary & Mechanics", summary: "Risa.", formula: "S + laugh + N", rules: [], examples: [], commonMistakes: [], topNotchUnitRef: "Unit 5" },
  { id: "sum2-6", bookLevelId: "summit2", bookTitle: "Summit 2", topicTitle: "Traveling", category: "Vocabulary & Mechanics", summary: "Viajes.", formula: "S + travel + Adv", rules: [], examples: [], commonMistakes: [], topNotchUnitRef: "Unit 6" },
  { id: "sum2-7", bookLevelId: "summit2", bookTitle: "Summit 2", topicTitle: "Mind Over Matter", category: "Vocabulary & Mechanics", summary: "Mente.", formula: "S + think + N", rules: [], examples: [], commonMistakes: [], topNotchUnitRef: "Unit 7" },
  { id: "sum2-8", bookLevelId: "summit2", bookTitle: "Summit 2", topicTitle: "Best", category: "Vocabulary & Mechanics", summary: "Productividad.", formula: "S + work + Adv", rules: [], examples: [], commonMistakes: [], topNotchUnitRef: "Unit 8" },
  { id: "sum2-9", bookLevelId: "summit2", bookTitle: "Summit 2", topicTitle: "Future", category: "Vocabulary & Mechanics", summary: "Futuro.", formula: "S + will + V", rules: [], examples: [], commonMistakes: [], topNotchUnitRef: "Unit 9" },
  { id: "sum2-10", bookLevelId: "summit2", bookTitle: "Summit 2", topicTitle: "Interconnected", category: "Vocabulary & Mechanics", summary: "Global.", formula: "S + visit + N", rules: [], examples: [], commonMistakes: [], topNotchUnitRef: "Unit 10" },
];

